### PR TITLE
hash index method was removed from ruby, use key method instead

### PR DESCRIPTION
**Pull request by jfqd**
Cause index method was removed from ruby hash we should use the key method instead

### CODE REVIEW

**Comment by codener** [comment]
Thanks for the report. We'll need to fix this in a way that's compatible with all Rubies (including 1.8.7). I'll do that, but it may take some time.

**Comment by jfqd** [comment]
@codener Sorry, my fault. I totaly forgot that ruby 1.8 is still a thing. The hash index method is deprecated since ruby 1.9. I extended the code to reflect the [possible usage of ruby 1.8](https://github.com/makandra/rails/pull/12/commits/ce68d20e9323703005bc9a7ee9a8d99b3dcd4b4d).

**Review by codener — COMMENTED** [review]
LGTM

**Comment by jfqd** [comment]
@codener If you need anything more for this PR let me know :-)

**Comment by codener** [comment]
I have published your commit(s), [now available in 2-3-lts](https://github.com/makandra/rails/tree/2-3-lts). Thank you!

**Comment by jfqd** [comment]
@codener Thx a lot!

**Pull request closed without merging**
